#
# Copyright © 2022, Staufi Tech - Switzerland
# All rights reserved.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#


FROM golang:alpine as builder

WORKDIR /var/build

COPY ./ src/

RUN cd src/ && go install && go build -o ../swiss-qr-bill


FROM alpine

ENV TZ=Europe/Zurich
RUN apk update && apk add --no-cache tzdata

WORKDIR /usr/local/bin/

COPY --from=builder /var/build/swiss-qr-bill /usr/local/bin/swiss-qr-bill
COPY ./sql/init.sql /usr/local/bin/sql/
COPY ./graphics/ /usr/local/bin/graphics/
COPY ./ttf/ /usr/local/bin/ttf/

EXPOSE 3000

CMD ./swiss-qr-bill